- name: "Timezone Playbook"
  hosts: all
  tasks:
   - name: Change Timezone
     timezone:
       name: America/Detroit
       debugger: always
     become: yes
     become_method: sudo 
   
   - stat: path=/home/woodsj/ANSIBLE/statfile.txt
     register: st
     
   - debug: var=st
