- name: "Timezone Playbook"
  hosts: localhost
  connection: local
  tasks:
   - name: Change Timezone
     community.general.timezone:
       name: America/Atka
     become: yes
     become_method: sudo 
     
   - stat: path=/home/woodsj/ANSIBLE/statfile.txt
     register: st
     
   - debug: var=st
